# Generated by Django 2.2 on 2019-04-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datePosted',
            new_name='date_posted',
        ),
    ]
